# Makefile.in generated by automake 1.11.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/libvispace
pkgincludedir = $(includedir)/libvispace
pkglibdir = $(libdir)/libvispace
pkglibexecdir = $(libexecdir)/libvispace
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
subdir = .
DIST_COMMON = $(am__configure_deps) $(srcdir)/../depcomp \
	$(srcdir)/../install-sh $(srcdir)/../missing \
	$(srcdir)/Makefile.am $(srcdir)/Makefile.in \
	$(top_srcdir)/configure
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.in
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__installdirs = "$(DESTDIR)$(libdir)"
LIBRARIES = $(lib_LIBRARIES)
AR = ar
ARFLAGS = cru
libvispace_a_AR = $(AR) $(ARFLAGS)
libvispace_a_LIBADD =
am_libvispace_a_OBJECTS = unit.$(OBJEXT) otu.$(OBJEXT) olp.$(OBJEXT) \
	ddm.$(OBJEXT) chassis.$(OBJEXT) sigmsg.$(OBJEXT) \
	shmutil.$(OBJEXT) mbusshm.$(OBJEXT) sysinfo.$(OBJEXT) \
	snmputil.$(OBJEXT) logutil.$(OBJEXT) dbutil.$(OBJEXT) \
	almutil.$(OBJEXT) visstr.$(OBJEXT) iniconf.$(OBJEXT) \
	shutils.$(OBJEXT) infoset.$(OBJEXT)
libvispace_a_OBJECTS = $(am_libvispace_a_OBJECTS)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/../depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
SOURCES = $(libvispace_a_SOURCES)
DIST_SOURCES = $(libvispace_a_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/visint/VisProj/src/missing --run aclocal-1.11
AMTAR = ${SHELL} /home/visint/VisProj/src/missing --run tar
AUTOCONF = ${SHELL} /home/visint/VisProj/src/missing --run autoconf
AUTOHEADER = ${SHELL} /home/visint/VisProj/src/missing --run autoheader
AUTOMAKE = ${SHELL} /home/visint/VisProj/src/missing --run automake-1.11
AWK = mawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libvispace\" -DVERSION=\"0.0.1\" -DSTDC_HEADERS=1
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/visint/VisProj/src/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = libvispace
PACKAGE_BUGREPORT = 
PACKAGE_NAME = 
PACKAGE_STRING = 
PACKAGE_TARNAME = 
PACKAGE_URL = 
PACKAGE_VERSION = 
PATH_SEPARATOR = :
RANLIB = ranlib
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 0.0.1
abs_builddir = /home/visint/VisProj/src/lib
abs_srcdir = /home/visint/VisProj/src/lib
abs_top_builddir = /home/visint/VisProj/src/lib
abs_top_srcdir = /home/visint/VisProj/src/lib
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/visint/VisProj/src/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = foreign
lib_LIBRARIES = libvispace.a
libvispace_a_SOURCES = ../unit/unitutil/unit.c ../unit/otu/otu.c ../unit/olp/olp.c ../unit/ddm/ddm.c ../unit/chassis/chassis.c\
../visipc/ipcutil/sigmsg.c ../visipc/ipcutil/shmutil.c ../visipc/ipcutil/mbusshm.c \
../sys/sysutil/sysinfo.c ../sys/sysutil/snmputil.c ../sys/sysutil/logutil.c \
../visdb/dbutil/dbutil.c ../visdb/dbutil/almutil.c ../visstr/visstr.c \
../utils/iniconf.c ../utils/shutils.c ../infoset/infoset.c

#LIBS= ../../visstr/libvisstr.a
#libutils_a_LDFLAGS = -version-info 0:0:0
INCLUDES = -I$(CURRENTPATH)./../include
all: all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
install-libLIBRARIES: $(lib_LIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(libdir)" || $(MKDIR_P) "$(DESTDIR)$(libdir)"
	@list='$(lib_LIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(INSTALL_DATA) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(INSTALL_DATA) $$list2 "$(DESTDIR)$(libdir)" || exit $$?; }
	@$(POST_INSTALL)
	@list='$(lib_LIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  if test -f $$p; then \
	    $(am__strip_dir) \
	    echo " ( cd '$(DESTDIR)$(libdir)' && $(RANLIB) $$f )"; \
	    ( cd "$(DESTDIR)$(libdir)" && $(RANLIB) $$f ) || exit $$?; \
	  else :; fi; \
	done

uninstall-libLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LIBRARIES)'; test -n "$(libdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	test -n "$$files" || exit 0; \
	echo " ( cd '$(DESTDIR)$(libdir)' && rm -f "$$files" )"; \
	cd "$(DESTDIR)$(libdir)" && rm -f $$files

clean-libLIBRARIES:
	-test -z "$(lib_LIBRARIES)" || rm -f $(lib_LIBRARIES)
libvispace.a: $(libvispace_a_OBJECTS) $(libvispace_a_DEPENDENCIES) 
	-rm -f libvispace.a
	$(libvispace_a_AR) libvispace.a $(libvispace_a_OBJECTS) $(libvispace_a_LIBADD)
	$(RANLIB) libvispace.a
	cp libvispace.a ../linuxlib
	cp libvispace.a /usr/local/lib
mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/almutil.Po
include ./$(DEPDIR)/chassis.Po
include ./$(DEPDIR)/dbutil.Po
include ./$(DEPDIR)/ddm.Po
include ./$(DEPDIR)/infoset.Po
include ./$(DEPDIR)/iniconf.Po
include ./$(DEPDIR)/logutil.Po
include ./$(DEPDIR)/mbusshm.Po
include ./$(DEPDIR)/olp.Po
include ./$(DEPDIR)/otu.Po
include ./$(DEPDIR)/shmutil.Po
include ./$(DEPDIR)/shutils.Po
include ./$(DEPDIR)/sigmsg.Po
include ./$(DEPDIR)/snmputil.Po
include ./$(DEPDIR)/sysinfo.Po
include ./$(DEPDIR)/unit.Po
include ./$(DEPDIR)/visstr.Po

.c.o:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

unit.o: ../unit/unitutil/unit.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT unit.o -MD -MP -MF $(DEPDIR)/unit.Tpo -c -o unit.o `test -f '../unit/unitutil/unit.c' || echo '$(srcdir)/'`../unit/unitutil/unit.c
	$(am__mv) $(DEPDIR)/unit.Tpo $(DEPDIR)/unit.Po
#	source='../unit/unitutil/unit.c' object='unit.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o unit.o `test -f '../unit/unitutil/unit.c' || echo '$(srcdir)/'`../unit/unitutil/unit.c

unit.obj: ../unit/unitutil/unit.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT unit.obj -MD -MP -MF $(DEPDIR)/unit.Tpo -c -o unit.obj `if test -f '../unit/unitutil/unit.c'; then $(CYGPATH_W) '../unit/unitutil/unit.c'; else $(CYGPATH_W) '$(srcdir)/../unit/unitutil/unit.c'; fi`
	$(am__mv) $(DEPDIR)/unit.Tpo $(DEPDIR)/unit.Po
#	source='../unit/unitutil/unit.c' object='unit.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o unit.obj `if test -f '../unit/unitutil/unit.c'; then $(CYGPATH_W) '../unit/unitutil/unit.c'; else $(CYGPATH_W) '$(srcdir)/../unit/unitutil/unit.c'; fi`

otu.o: ../unit/otu/otu.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT otu.o -MD -MP -MF $(DEPDIR)/otu.Tpo -c -o otu.o `test -f '../unit/otu/otu.c' || echo '$(srcdir)/'`../unit/otu/otu.c
	$(am__mv) $(DEPDIR)/otu.Tpo $(DEPDIR)/otu.Po
#	source='../unit/otu/otu.c' object='otu.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o otu.o `test -f '../unit/otu/otu.c' || echo '$(srcdir)/'`../unit/otu/otu.c

otu.obj: ../unit/otu/otu.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT otu.obj -MD -MP -MF $(DEPDIR)/otu.Tpo -c -o otu.obj `if test -f '../unit/otu/otu.c'; then $(CYGPATH_W) '../unit/otu/otu.c'; else $(CYGPATH_W) '$(srcdir)/../unit/otu/otu.c'; fi`
	$(am__mv) $(DEPDIR)/otu.Tpo $(DEPDIR)/otu.Po
#	source='../unit/otu/otu.c' object='otu.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o otu.obj `if test -f '../unit/otu/otu.c'; then $(CYGPATH_W) '../unit/otu/otu.c'; else $(CYGPATH_W) '$(srcdir)/../unit/otu/otu.c'; fi`

olp.o: ../unit/olp/olp.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT olp.o -MD -MP -MF $(DEPDIR)/olp.Tpo -c -o olp.o `test -f '../unit/olp/olp.c' || echo '$(srcdir)/'`../unit/olp/olp.c
	$(am__mv) $(DEPDIR)/olp.Tpo $(DEPDIR)/olp.Po
#	source='../unit/olp/olp.c' object='olp.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o olp.o `test -f '../unit/olp/olp.c' || echo '$(srcdir)/'`../unit/olp/olp.c

olp.obj: ../unit/olp/olp.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT olp.obj -MD -MP -MF $(DEPDIR)/olp.Tpo -c -o olp.obj `if test -f '../unit/olp/olp.c'; then $(CYGPATH_W) '../unit/olp/olp.c'; else $(CYGPATH_W) '$(srcdir)/../unit/olp/olp.c'; fi`
	$(am__mv) $(DEPDIR)/olp.Tpo $(DEPDIR)/olp.Po
#	source='../unit/olp/olp.c' object='olp.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o olp.obj `if test -f '../unit/olp/olp.c'; then $(CYGPATH_W) '../unit/olp/olp.c'; else $(CYGPATH_W) '$(srcdir)/../unit/olp/olp.c'; fi`

ddm.o: ../unit/ddm/ddm.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT ddm.o -MD -MP -MF $(DEPDIR)/ddm.Tpo -c -o ddm.o `test -f '../unit/ddm/ddm.c' || echo '$(srcdir)/'`../unit/ddm/ddm.c
	$(am__mv) $(DEPDIR)/ddm.Tpo $(DEPDIR)/ddm.Po
#	source='../unit/ddm/ddm.c' object='ddm.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o ddm.o `test -f '../unit/ddm/ddm.c' || echo '$(srcdir)/'`../unit/ddm/ddm.c

ddm.obj: ../unit/ddm/ddm.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT ddm.obj -MD -MP -MF $(DEPDIR)/ddm.Tpo -c -o ddm.obj `if test -f '../unit/ddm/ddm.c'; then $(CYGPATH_W) '../unit/ddm/ddm.c'; else $(CYGPATH_W) '$(srcdir)/../unit/ddm/ddm.c'; fi`
	$(am__mv) $(DEPDIR)/ddm.Tpo $(DEPDIR)/ddm.Po
#	source='../unit/ddm/ddm.c' object='ddm.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o ddm.obj `if test -f '../unit/ddm/ddm.c'; then $(CYGPATH_W) '../unit/ddm/ddm.c'; else $(CYGPATH_W) '$(srcdir)/../unit/ddm/ddm.c'; fi`

chassis.o: ../unit/chassis/chassis.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT chassis.o -MD -MP -MF $(DEPDIR)/chassis.Tpo -c -o chassis.o `test -f '../unit/chassis/chassis.c' || echo '$(srcdir)/'`../unit/chassis/chassis.c
	$(am__mv) $(DEPDIR)/chassis.Tpo $(DEPDIR)/chassis.Po
#	source='../unit/chassis/chassis.c' object='chassis.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o chassis.o `test -f '../unit/chassis/chassis.c' || echo '$(srcdir)/'`../unit/chassis/chassis.c

chassis.obj: ../unit/chassis/chassis.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT chassis.obj -MD -MP -MF $(DEPDIR)/chassis.Tpo -c -o chassis.obj `if test -f '../unit/chassis/chassis.c'; then $(CYGPATH_W) '../unit/chassis/chassis.c'; else $(CYGPATH_W) '$(srcdir)/../unit/chassis/chassis.c'; fi`
	$(am__mv) $(DEPDIR)/chassis.Tpo $(DEPDIR)/chassis.Po
#	source='../unit/chassis/chassis.c' object='chassis.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o chassis.obj `if test -f '../unit/chassis/chassis.c'; then $(CYGPATH_W) '../unit/chassis/chassis.c'; else $(CYGPATH_W) '$(srcdir)/../unit/chassis/chassis.c'; fi`

sigmsg.o: ../visipc/ipcutil/sigmsg.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sigmsg.o -MD -MP -MF $(DEPDIR)/sigmsg.Tpo -c -o sigmsg.o `test -f '../visipc/ipcutil/sigmsg.c' || echo '$(srcdir)/'`../visipc/ipcutil/sigmsg.c
	$(am__mv) $(DEPDIR)/sigmsg.Tpo $(DEPDIR)/sigmsg.Po
#	source='../visipc/ipcutil/sigmsg.c' object='sigmsg.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sigmsg.o `test -f '../visipc/ipcutil/sigmsg.c' || echo '$(srcdir)/'`../visipc/ipcutil/sigmsg.c

sigmsg.obj: ../visipc/ipcutil/sigmsg.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sigmsg.obj -MD -MP -MF $(DEPDIR)/sigmsg.Tpo -c -o sigmsg.obj `if test -f '../visipc/ipcutil/sigmsg.c'; then $(CYGPATH_W) '../visipc/ipcutil/sigmsg.c'; else $(CYGPATH_W) '$(srcdir)/../visipc/ipcutil/sigmsg.c'; fi`
	$(am__mv) $(DEPDIR)/sigmsg.Tpo $(DEPDIR)/sigmsg.Po
#	source='../visipc/ipcutil/sigmsg.c' object='sigmsg.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sigmsg.obj `if test -f '../visipc/ipcutil/sigmsg.c'; then $(CYGPATH_W) '../visipc/ipcutil/sigmsg.c'; else $(CYGPATH_W) '$(srcdir)/../visipc/ipcutil/sigmsg.c'; fi`

shmutil.o: ../visipc/ipcutil/shmutil.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT shmutil.o -MD -MP -MF $(DEPDIR)/shmutil.Tpo -c -o shmutil.o `test -f '../visipc/ipcutil/shmutil.c' || echo '$(srcdir)/'`../visipc/ipcutil/shmutil.c
	$(am__mv) $(DEPDIR)/shmutil.Tpo $(DEPDIR)/shmutil.Po
#	source='../visipc/ipcutil/shmutil.c' object='shmutil.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o shmutil.o `test -f '../visipc/ipcutil/shmutil.c' || echo '$(srcdir)/'`../visipc/ipcutil/shmutil.c

shmutil.obj: ../visipc/ipcutil/shmutil.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT shmutil.obj -MD -MP -MF $(DEPDIR)/shmutil.Tpo -c -o shmutil.obj `if test -f '../visipc/ipcutil/shmutil.c'; then $(CYGPATH_W) '../visipc/ipcutil/shmutil.c'; else $(CYGPATH_W) '$(srcdir)/../visipc/ipcutil/shmutil.c'; fi`
	$(am__mv) $(DEPDIR)/shmutil.Tpo $(DEPDIR)/shmutil.Po
#	source='../visipc/ipcutil/shmutil.c' object='shmutil.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o shmutil.obj `if test -f '../visipc/ipcutil/shmutil.c'; then $(CYGPATH_W) '../visipc/ipcutil/shmutil.c'; else $(CYGPATH_W) '$(srcdir)/../visipc/ipcutil/shmutil.c'; fi`

mbusshm.o: ../visipc/ipcutil/mbusshm.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT mbusshm.o -MD -MP -MF $(DEPDIR)/mbusshm.Tpo -c -o mbusshm.o `test -f '../visipc/ipcutil/mbusshm.c' || echo '$(srcdir)/'`../visipc/ipcutil/mbusshm.c
	$(am__mv) $(DEPDIR)/mbusshm.Tpo $(DEPDIR)/mbusshm.Po
#	source='../visipc/ipcutil/mbusshm.c' object='mbusshm.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o mbusshm.o `test -f '../visipc/ipcutil/mbusshm.c' || echo '$(srcdir)/'`../visipc/ipcutil/mbusshm.c

mbusshm.obj: ../visipc/ipcutil/mbusshm.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT mbusshm.obj -MD -MP -MF $(DEPDIR)/mbusshm.Tpo -c -o mbusshm.obj `if test -f '../visipc/ipcutil/mbusshm.c'; then $(CYGPATH_W) '../visipc/ipcutil/mbusshm.c'; else $(CYGPATH_W) '$(srcdir)/../visipc/ipcutil/mbusshm.c'; fi`
	$(am__mv) $(DEPDIR)/mbusshm.Tpo $(DEPDIR)/mbusshm.Po
#	source='../visipc/ipcutil/mbusshm.c' object='mbusshm.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o mbusshm.obj `if test -f '../visipc/ipcutil/mbusshm.c'; then $(CYGPATH_W) '../visipc/ipcutil/mbusshm.c'; else $(CYGPATH_W) '$(srcdir)/../visipc/ipcutil/mbusshm.c'; fi`

sysinfo.o: ../sys/sysutil/sysinfo.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sysinfo.o -MD -MP -MF $(DEPDIR)/sysinfo.Tpo -c -o sysinfo.o `test -f '../sys/sysutil/sysinfo.c' || echo '$(srcdir)/'`../sys/sysutil/sysinfo.c
	$(am__mv) $(DEPDIR)/sysinfo.Tpo $(DEPDIR)/sysinfo.Po
#	source='../sys/sysutil/sysinfo.c' object='sysinfo.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sysinfo.o `test -f '../sys/sysutil/sysinfo.c' || echo '$(srcdir)/'`../sys/sysutil/sysinfo.c

sysinfo.obj: ../sys/sysutil/sysinfo.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sysinfo.obj -MD -MP -MF $(DEPDIR)/sysinfo.Tpo -c -o sysinfo.obj `if test -f '../sys/sysutil/sysinfo.c'; then $(CYGPATH_W) '../sys/sysutil/sysinfo.c'; else $(CYGPATH_W) '$(srcdir)/../sys/sysutil/sysinfo.c'; fi`
	$(am__mv) $(DEPDIR)/sysinfo.Tpo $(DEPDIR)/sysinfo.Po
#	source='../sys/sysutil/sysinfo.c' object='sysinfo.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sysinfo.obj `if test -f '../sys/sysutil/sysinfo.c'; then $(CYGPATH_W) '../sys/sysutil/sysinfo.c'; else $(CYGPATH_W) '$(srcdir)/../sys/sysutil/sysinfo.c'; fi`

snmputil.o: ../sys/sysutil/snmputil.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT snmputil.o -MD -MP -MF $(DEPDIR)/snmputil.Tpo -c -o snmputil.o `test -f '../sys/sysutil/snmputil.c' || echo '$(srcdir)/'`../sys/sysutil/snmputil.c
	$(am__mv) $(DEPDIR)/snmputil.Tpo $(DEPDIR)/snmputil.Po
#	source='../sys/sysutil/snmputil.c' object='snmputil.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o snmputil.o `test -f '../sys/sysutil/snmputil.c' || echo '$(srcdir)/'`../sys/sysutil/snmputil.c

snmputil.obj: ../sys/sysutil/snmputil.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT snmputil.obj -MD -MP -MF $(DEPDIR)/snmputil.Tpo -c -o snmputil.obj `if test -f '../sys/sysutil/snmputil.c'; then $(CYGPATH_W) '../sys/sysutil/snmputil.c'; else $(CYGPATH_W) '$(srcdir)/../sys/sysutil/snmputil.c'; fi`
	$(am__mv) $(DEPDIR)/snmputil.Tpo $(DEPDIR)/snmputil.Po
#	source='../sys/sysutil/snmputil.c' object='snmputil.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o snmputil.obj `if test -f '../sys/sysutil/snmputil.c'; then $(CYGPATH_W) '../sys/sysutil/snmputil.c'; else $(CYGPATH_W) '$(srcdir)/../sys/sysutil/snmputil.c'; fi`

logutil.o: ../sys/sysutil/logutil.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT logutil.o -MD -MP -MF $(DEPDIR)/logutil.Tpo -c -o logutil.o `test -f '../sys/sysutil/logutil.c' || echo '$(srcdir)/'`../sys/sysutil/logutil.c
	$(am__mv) $(DEPDIR)/logutil.Tpo $(DEPDIR)/logutil.Po
#	source='../sys/sysutil/logutil.c' object='logutil.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o logutil.o `test -f '../sys/sysutil/logutil.c' || echo '$(srcdir)/'`../sys/sysutil/logutil.c

logutil.obj: ../sys/sysutil/logutil.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT logutil.obj -MD -MP -MF $(DEPDIR)/logutil.Tpo -c -o logutil.obj `if test -f '../sys/sysutil/logutil.c'; then $(CYGPATH_W) '../sys/sysutil/logutil.c'; else $(CYGPATH_W) '$(srcdir)/../sys/sysutil/logutil.c'; fi`
	$(am__mv) $(DEPDIR)/logutil.Tpo $(DEPDIR)/logutil.Po
#	source='../sys/sysutil/logutil.c' object='logutil.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o logutil.obj `if test -f '../sys/sysutil/logutil.c'; then $(CYGPATH_W) '../sys/sysutil/logutil.c'; else $(CYGPATH_W) '$(srcdir)/../sys/sysutil/logutil.c'; fi`

dbutil.o: ../visdb/dbutil/dbutil.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT dbutil.o -MD -MP -MF $(DEPDIR)/dbutil.Tpo -c -o dbutil.o `test -f '../visdb/dbutil/dbutil.c' || echo '$(srcdir)/'`../visdb/dbutil/dbutil.c
	$(am__mv) $(DEPDIR)/dbutil.Tpo $(DEPDIR)/dbutil.Po
#	source='../visdb/dbutil/dbutil.c' object='dbutil.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o dbutil.o `test -f '../visdb/dbutil/dbutil.c' || echo '$(srcdir)/'`../visdb/dbutil/dbutil.c

dbutil.obj: ../visdb/dbutil/dbutil.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT dbutil.obj -MD -MP -MF $(DEPDIR)/dbutil.Tpo -c -o dbutil.obj `if test -f '../visdb/dbutil/dbutil.c'; then $(CYGPATH_W) '../visdb/dbutil/dbutil.c'; else $(CYGPATH_W) '$(srcdir)/../visdb/dbutil/dbutil.c'; fi`
	$(am__mv) $(DEPDIR)/dbutil.Tpo $(DEPDIR)/dbutil.Po
#	source='../visdb/dbutil/dbutil.c' object='dbutil.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o dbutil.obj `if test -f '../visdb/dbutil/dbutil.c'; then $(CYGPATH_W) '../visdb/dbutil/dbutil.c'; else $(CYGPATH_W) '$(srcdir)/../visdb/dbutil/dbutil.c'; fi`

almutil.o: ../visdb/dbutil/almutil.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT almutil.o -MD -MP -MF $(DEPDIR)/almutil.Tpo -c -o almutil.o `test -f '../visdb/dbutil/almutil.c' || echo '$(srcdir)/'`../visdb/dbutil/almutil.c
	$(am__mv) $(DEPDIR)/almutil.Tpo $(DEPDIR)/almutil.Po
#	source='../visdb/dbutil/almutil.c' object='almutil.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o almutil.o `test -f '../visdb/dbutil/almutil.c' || echo '$(srcdir)/'`../visdb/dbutil/almutil.c

almutil.obj: ../visdb/dbutil/almutil.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT almutil.obj -MD -MP -MF $(DEPDIR)/almutil.Tpo -c -o almutil.obj `if test -f '../visdb/dbutil/almutil.c'; then $(CYGPATH_W) '../visdb/dbutil/almutil.c'; else $(CYGPATH_W) '$(srcdir)/../visdb/dbutil/almutil.c'; fi`
	$(am__mv) $(DEPDIR)/almutil.Tpo $(DEPDIR)/almutil.Po
#	source='../visdb/dbutil/almutil.c' object='almutil.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o almutil.obj `if test -f '../visdb/dbutil/almutil.c'; then $(CYGPATH_W) '../visdb/dbutil/almutil.c'; else $(CYGPATH_W) '$(srcdir)/../visdb/dbutil/almutil.c'; fi`

visstr.o: ../visstr/visstr.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT visstr.o -MD -MP -MF $(DEPDIR)/visstr.Tpo -c -o visstr.o `test -f '../visstr/visstr.c' || echo '$(srcdir)/'`../visstr/visstr.c
	$(am__mv) $(DEPDIR)/visstr.Tpo $(DEPDIR)/visstr.Po
#	source='../visstr/visstr.c' object='visstr.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o visstr.o `test -f '../visstr/visstr.c' || echo '$(srcdir)/'`../visstr/visstr.c

visstr.obj: ../visstr/visstr.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT visstr.obj -MD -MP -MF $(DEPDIR)/visstr.Tpo -c -o visstr.obj `if test -f '../visstr/visstr.c'; then $(CYGPATH_W) '../visstr/visstr.c'; else $(CYGPATH_W) '$(srcdir)/../visstr/visstr.c'; fi`
	$(am__mv) $(DEPDIR)/visstr.Tpo $(DEPDIR)/visstr.Po
#	source='../visstr/visstr.c' object='visstr.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o visstr.obj `if test -f '../visstr/visstr.c'; then $(CYGPATH_W) '../visstr/visstr.c'; else $(CYGPATH_W) '$(srcdir)/../visstr/visstr.c'; fi`

iniconf.o: ../utils/iniconf.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT iniconf.o -MD -MP -MF $(DEPDIR)/iniconf.Tpo -c -o iniconf.o `test -f '../utils/iniconf.c' || echo '$(srcdir)/'`../utils/iniconf.c
	$(am__mv) $(DEPDIR)/iniconf.Tpo $(DEPDIR)/iniconf.Po
#	source='../utils/iniconf.c' object='iniconf.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o iniconf.o `test -f '../utils/iniconf.c' || echo '$(srcdir)/'`../utils/iniconf.c

iniconf.obj: ../utils/iniconf.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT iniconf.obj -MD -MP -MF $(DEPDIR)/iniconf.Tpo -c -o iniconf.obj `if test -f '../utils/iniconf.c'; then $(CYGPATH_W) '../utils/iniconf.c'; else $(CYGPATH_W) '$(srcdir)/../utils/iniconf.c'; fi`
	$(am__mv) $(DEPDIR)/iniconf.Tpo $(DEPDIR)/iniconf.Po
#	source='../utils/iniconf.c' object='iniconf.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o iniconf.obj `if test -f '../utils/iniconf.c'; then $(CYGPATH_W) '../utils/iniconf.c'; else $(CYGPATH_W) '$(srcdir)/../utils/iniconf.c'; fi`

shutils.o: ../utils/shutils.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT shutils.o -MD -MP -MF $(DEPDIR)/shutils.Tpo -c -o shutils.o `test -f '../utils/shutils.c' || echo '$(srcdir)/'`../utils/shutils.c
	$(am__mv) $(DEPDIR)/shutils.Tpo $(DEPDIR)/shutils.Po
#	source='../utils/shutils.c' object='shutils.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o shutils.o `test -f '../utils/shutils.c' || echo '$(srcdir)/'`../utils/shutils.c

shutils.obj: ../utils/shutils.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT shutils.obj -MD -MP -MF $(DEPDIR)/shutils.Tpo -c -o shutils.obj `if test -f '../utils/shutils.c'; then $(CYGPATH_W) '../utils/shutils.c'; else $(CYGPATH_W) '$(srcdir)/../utils/shutils.c'; fi`
	$(am__mv) $(DEPDIR)/shutils.Tpo $(DEPDIR)/shutils.Po
#	source='../utils/shutils.c' object='shutils.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o shutils.obj `if test -f '../utils/shutils.c'; then $(CYGPATH_W) '../utils/shutils.c'; else $(CYGPATH_W) '$(srcdir)/../utils/shutils.c'; fi`

infoset.o: ../infoset/infoset.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT infoset.o -MD -MP -MF $(DEPDIR)/infoset.Tpo -c -o infoset.o `test -f '../infoset/infoset.c' || echo '$(srcdir)/'`../infoset/infoset.c
	$(am__mv) $(DEPDIR)/infoset.Tpo $(DEPDIR)/infoset.Po
#	source='../infoset/infoset.c' object='infoset.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o infoset.o `test -f '../infoset/infoset.c' || echo '$(srcdir)/'`../infoset/infoset.c

infoset.obj: ../infoset/infoset.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT infoset.obj -MD -MP -MF $(DEPDIR)/infoset.Tpo -c -o infoset.obj `if test -f '../infoset/infoset.c'; then $(CYGPATH_W) '../infoset/infoset.c'; else $(CYGPATH_W) '$(srcdir)/../infoset/infoset.c'; fi`
	$(am__mv) $(DEPDIR)/infoset.Tpo $(DEPDIR)/infoset.Po
#	source='../infoset/infoset.c' object='infoset.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o infoset.obj `if test -f '../infoset/infoset.c'; then $(CYGPATH_W) '../infoset/infoset.c'; else $(CYGPATH_W) '$(srcdir)/../infoset/infoset.c'; fi`

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod u+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@$(am__cd) '$(distuninstallcheck_dir)' \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(LIBRARIES)
installdirs:
	for dir in "$(DESTDIR)$(libdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libLIBRARIES mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-libLIBRARIES

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-libLIBRARIES

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-generic clean-libLIBRARIES ctags dist dist-all \
	dist-bzip2 dist-gzip dist-lzma dist-shar dist-tarZ dist-xz \
	dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am \
	install-libLIBRARIES install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-libLIBRARIES


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
